#!/usr/bin/env bash

#
# Setup script which installs git hooks under .git/hooks of the Git repository
# in which this script is run.
#
# Exit:
#   0 - on success
#   1 - on error

# git > 1.8.2
GIT_REQUIRED_VERSION='1.8.2'
git_version=$(git --version | awk '{print $3}' | awk -F'.' '{print $1"."$2"."$3}')
if [[ ${git_version} < ${GIT_REQUIRED_VERSION} ]]; then
    echo "[ERROR] $(which git) is older than ${GIT_REQUIRED_VERSION}"
    echo "[ERROR] Please carry out the following steps:"
    echo ""
    echo "[ERROR] 1. Upgrade git to +${GIT_REQUIRED_VERSION} http://git-scm.com/downloads"
    echo '[ERROR] 2. Once installed add the following to your ~/.bash_profile'
    echo '[ERROR]       export PATH=/usr/local/git/bin:$PATH'
    echo '[ERROR] 3. Within IntelliJ preferences change "Path to Git executable"'
    echo '[ERROR]    to be /usr/local/git/bin/git'
    exit 1
else
    echo "# found git ${git_version} > ${GIT_REQUIRED_VERSION}" 
fi

git_top_path=$(git rev-parse --show-toplevel)
source_git_hook_path="${git_top_path}/git-hooks"
target_git_hook_path="${git_top_path}/.git/hooks"

# Initial validation
if [ ! -d "${git_top_path}" ]; then
    echo "[ERROR] this command must be run from the top level of checkout Git repository"
    exit 1
fi
if [ ! -e "${source_git_hook_path}" ]; then
    echo "[ERROR] cannot find ${source_git_hook_path}"
    exit 1
fi

# Set up git hooks
echo "# setting up git hook for ${git_top_path}"
[ -f "${target_git_hook_path}" ] && mkdir -p "${target_git_hook_path}"
rm -f "${target_git_hook_path}/pre-commit"
ln -s "${source_git_hook_path}/pre-commit" "${target_git_hook_path}/pre-commit"
rm -f "${target_git_hook_path}/pre-push"
ln -s "${source_git_hook_path}/pre-push" "${target_git_hook_path}/pre-push"

# Sanity-check the results
if [ ! -h "${target_git_hook_path}/pre-commit" ]; then
    echo "[ERROR] failed to install git pre-commit"
    exit 1
fi
if [ ! -h "${target_git_hook_path}/pre-push" ]; then
    echo "[ERROR] failed to install git pre-push"
    exit 1
fi
echo '# setup git-hooks successful'
