# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mockserver.api.expectation_api import ExpectationApi


class TestExpectationApi(unittest.TestCase):
    """ExpectationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExpectationApi()

    def tearDown(self) -> None:
        pass

    def test_mockserver_expectation_put(self) -> None:
        """Test case for mockserver_expectation_put

        create expectation
        """
        pass

    def test_mockserver_openapi_put(self) -> None:
        """Test case for mockserver_openapi_put

        create expectations from OpenAPI or Swagger
        """
        pass


if __name__ == '__main__':
    unittest.main()
