# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mockserver.models.body_any_of1 import BodyAnyOf1

class TestBodyAnyOf1(unittest.TestCase):
    """BodyAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyAnyOf1:
        """Test BodyAnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyAnyOf1`
        """
        model = BodyAnyOf1()
        if include_optional:
            return BodyAnyOf1(
                var_not = True,
                type = 'JSON',
                var_json = '',
                content_type = '',
                match_type = 'STRICT',
                match_numbers_as_strings = True
            )
        else:
            return BodyAnyOf1(
        )
        """

    def testBodyAnyOf1(self):
        """Test BodyAnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
