# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mockserver.api.verify_api import VerifyApi


class TestVerifyApi(unittest.TestCase):
    """VerifyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VerifyApi()

    def tearDown(self) -> None:
        pass

    def test_mockserver_verify_put(self) -> None:
        """Test case for mockserver_verify_put

        verify a request has been received a specific number of times
        """
        pass

    def test_mockserver_verify_sequence_put(self) -> None:
        """Test case for mockserver_verify_sequence_put

        verify a sequence of request has been received in the specific order
        """
        pass


if __name__ == '__main__':
    unittest.main()
