# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mockserver.api.control_api import ControlApi


class TestControlApi(unittest.TestCase):
    """ControlApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ControlApi()

    def tearDown(self) -> None:
        pass

    def test_mockserver_bind_put(self) -> None:
        """Test case for mockserver_bind_put

        bind additional listening ports
        """
        pass

    def test_mockserver_clear_put(self) -> None:
        """Test case for mockserver_clear_put

        clears expectations and recorded requests that match the request matcher
        """
        pass

    def test_mockserver_reset_put(self) -> None:
        """Test case for mockserver_reset_put

        clears all expectations and recorded requests
        """
        pass

    def test_mockserver_retrieve_put(self) -> None:
        """Test case for mockserver_retrieve_put

        retrieve recorded requests, active expectations, recorded expectations or log messages
        """
        pass

    def test_mockserver_status_put(self) -> None:
        """Test case for mockserver_status_put

        return listening ports
        """
        pass

    def test_mockserver_stop_put(self) -> None:
        """Test case for mockserver_stop_put

        stop running process
        """
        pass


if __name__ == '__main__':
    unittest.main()
