# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mockserver.models.mockserver_clear_put_request import MockserverClearPutRequest

class TestMockserverClearPutRequest(unittest.TestCase):
    """MockserverClearPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MockserverClearPutRequest:
        """Test MockserverClearPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MockserverClearPutRequest`
        """
        model = MockserverClearPutRequest()
        if include_optional:
            return MockserverClearPutRequest(
                secure = True,
                keep_alive = True,
                method = None,
                path = None,
                path_parameters = None,
                query_string_parameters = None,
                body = None,
                headers = None,
                cookies = None,
                socket_address = mockserver.models.socket_address.SocketAddress(
                    host = '', 
                    port = 56, 
                    scheme = 'HTTP', ),
                protocol = 'HTTP_1_1',
                spec_url_or_payload = '',
                operation_id = '',
                id = ''
            )
        else:
            return MockserverClearPutRequest(
                id = '',
        )
        """

    def testMockserverClearPutRequest(self):
        """Test MockserverClearPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
