# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mockserver.models.http_override_forwarded_request_one_of1 import HttpOverrideForwardedRequestOneOf1

class TestHttpOverrideForwardedRequestOneOf1(unittest.TestCase):
    """HttpOverrideForwardedRequestOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpOverrideForwardedRequestOneOf1:
        """Test HttpOverrideForwardedRequestOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpOverrideForwardedRequestOneOf1`
        """
        model = HttpOverrideForwardedRequestOneOf1()
        if include_optional:
            return HttpOverrideForwardedRequestOneOf1(
                delay = mockserver.models.delay.Delay(
                    time_unit = '', 
                    value = 56, ),
                http_request = mockserver.models.http_request.HttpRequest(
                    secure = True, 
                    keep_alive = True, 
                    method = null, 
                    path = null, 
                    path_parameters = null, 
                    query_string_parameters = null, 
                    body = null, 
                    headers = null, 
                    cookies = null, 
                    socket_address = mockserver.models.socket_address.SocketAddress(
                        host = '', 
                        port = 56, 
                        scheme = 'HTTP', ), 
                    protocol = 'HTTP_1_1', ),
                http_response = mockserver.models.http_response.HttpResponse(
                    delay = mockserver.models.delay.Delay(
                        time_unit = '', 
                        value = 56, ), 
                    body = null, 
                    cookies = null, 
                    connection_options = mockserver.models.connection_options.ConnectionOptions(
                        suppress_content_length_header = True, 
                        content_length_header_override = 56, 
                        suppress_connection_header = True, 
                        chunk_size = 56, 
                        keep_alive_override = True, 
                        close_socket = True, 
                        close_socket_delay = mockserver.models.delay.Delay(
                            time_unit = '', 
                            value = 56, ), ), 
                    headers = null, 
                    status_code = 56, 
                    reason_phrase = '', )
            )
        else:
            return HttpOverrideForwardedRequestOneOf1(
        )
        """

    def testHttpOverrideForwardedRequestOneOf1(self):
        """Test HttpOverrideForwardedRequestOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
