steps:
  - label: ":docker: Build maven CI image"
    command: ".buildkite/scripts/steps/maven-image-build.sh"
    timeout_in_minutes: 30

  - wait

  - label: ":docker: Push maven CI image"
    if: "build.branch == 'master'"
    command: ".buildkite/scripts/steps/maven-image-push.sh"
    timeout_in_minutes: 10
