steps:
  - label: ":python: Python client unit tests"
    command: ".buildkite/scripts/steps/python-unit-test.sh"
    timeout_in_minutes: 10

  - label: ":python: Python client integration tests"
    command: ".buildkite/scripts/steps/python-integration-test.sh"
    timeout_in_minutes: 10
