steps:
  - label: ":react: UI lint and typecheck"
    commands:
      - "cd mockserver-ui"
      - "npm ci"
      - "npm run lint"
      - "npm run typecheck"
    timeout_in_minutes: 10

  - label: ":jest: UI tests"
    commands:
      - "cd mockserver-ui"
      - "npm ci"
      - "npm test"
    timeout_in_minutes: 10

  - label: ":package: UI build"
    commands:
      - "cd mockserver-ui"
      - "npm ci"
      - "npm run build"
    timeout_in_minutes: 10
