steps:
  - label: ":node: client-node lint and typecheck"
    command: ".buildkite/scripts/steps/node-client-lint.sh"
    timeout_in_minutes: 10

  - label: ":node: node launcher lint"
    command: ".buildkite/scripts/steps/node-launcher-lint.sh"
    timeout_in_minutes: 10
