steps:
  - label: ":docker: update docker image"
    command: "docker pull mockserver/mockserver:maven"

  - wait

  - label: ":maven: maven-plugin build"
    command: ".buildkite/scripts/steps/maven-plugin-build.sh"
    artifact_paths:
      - "mockserver-maven-plugin/**/TEST-*.xml"
    timeout_in_minutes: 45

  - wait: ~
    continue_on_failure: true

  - label: ":junit: annotate test results"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "mockserver-maven-plugin/**/TEST-*.xml"
          always-annotate: true
          fail-build-on-error: false
