steps:
  - label: ":lint-roller: opencode config"
    command: "./scripts/validate_opencode_config.sh"
    timeout_in_minutes: 2

  - label: ":docker: update docker image"
    command: "docker pull mockserver/mockserver:maven"

  - wait

  - label: ":maven: build"
    command: "docker run --memory=14g --memory-swap=14g --oom-kill-disable=false -v $(pwd):/build/mockserver -w /build/mockserver -a stdout -a stderr -e BUILDKITE_BRANCH=$BUILDKITE_BRANCH mockserver/mockserver:maven /build/mockserver/scripts/buildkite_quick_build.sh"
    artifact_paths:
      - "**/*.log"
      - "**/target/surefire-reports/TEST-*.xml"
      - "**/target/surefire-reports/*-output.txt"
      - "**/target/failsafe-reports/TEST-*.xml"
      - "**/target/failsafe-reports/*-output.txt"
    timeout_in_minutes: 60

  - wait: ~
    continue_on_failure: true

  - label: ":junit: annotate test results"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "**/target/*-reports/TEST-*.xml"
          always-annotate: true

  - wait

  - label: ":nexus: deploy snapshot to Sonatype"
    if: "build.branch == 'master'"
    command: ".buildkite/scripts/deploy-snapshot.sh"
    timeout_in_minutes: 30

  - label: ":docker: build and push :latest"
    if: "build.branch == 'master'"
    command: ".buildkite/scripts/docker-push-latest.sh"
    timeout_in_minutes: 15
