steps:
  - label: ":react: UI lint and typecheck"
    command: ".buildkite/scripts/steps/ui-lint.sh"
    timeout_in_minutes: 10

  - label: ":jest: UI tests"
    command: ".buildkite/scripts/steps/ui-test.sh"
    timeout_in_minutes: 10

  - label: ":package: UI build"
    command: ".buildkite/scripts/steps/ui-build.sh"
    timeout_in_minutes: 10
