steps:
  - label: ":lint-roller: opencode config"
    command: ".buildkite/scripts/steps/java-validate-config.sh"
    timeout_in_minutes: 5

  - label: ":docker: update docker image"
    command: "docker pull mockserver/mockserver:maven"

  - wait

  - label: ":maven: build"
    command: ".buildkite/scripts/steps/java-build.sh"
    artifact_paths:
      - "**/*.log"
      - "**/target/surefire-reports/TEST-*.xml"
      - "**/target/surefire-reports/*-output.txt"
      - "**/target/failsafe-reports/TEST-*.xml"
      - "**/target/failsafe-reports/*-output.txt"
      - "mockserver/mockserver-netty/target/mockserver-netty-*-shaded.jar"
    timeout_in_minutes: 60

  - wait: ~
    continue_on_failure: true

  - label: ":junit: annotate test results"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "**/target/*-reports/TEST-*.xml"
          always-annotate: true

  - wait

  - label: ":nexus: deploy snapshot to Sonatype"
    if: "build.branch == 'master'"
    command: ".buildkite/scripts/steps/java-deploy-snapshot.sh"
    timeout_in_minutes: 30

  - label: ":docker: container integration tests"
    if: "build.branch == 'master'"
    command: ".buildkite/scripts/steps/container-tests-run.sh"
    timeout_in_minutes: 30

  - label: ":docker: build and push :snapshot"
    if: "build.branch == 'master'"
    command: ".buildkite/scripts/steps/java-docker-push-snapshot.sh"
    timeout_in_minutes: 30
