steps:
  - label: ":ruby: Ruby client unit tests"
    command: ".buildkite/scripts/steps/ruby-unit-test.sh"
    timeout_in_minutes: 10

  - label: ":ruby: Ruby client integration tests"
    command: ".buildkite/scripts/steps/ruby-integration-test.sh"
    timeout_in_minutes: 10
