steps:
  - group: ":mag: Release preflight"
    steps:
      - label: ":mag: Preflight (release queue)"
        command: ".buildkite/scripts/release-runner.sh preflight"
        timeout_in_minutes: 5
        agents:
          queue: "release"

      - label: ":mag: Preflight (default queue)"
        command: ".buildkite/scripts/release-runner.sh preflight"
        timeout_in_minutes: 5
