steps:
  - group: ":mag: Release preflight"
    steps:
      - label: ":mag: Preflight (release queue)"
        command: "scripts/ci/release/preflight.sh release"
        timeout_in_minutes: 5
        agents:
          queue: "release"

      - label: ":mag: Preflight (default queue)"
        command: "scripts/ci/release/preflight.sh default"
        timeout_in_minutes: 5
