# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, Optional
from mockserver.models.body_any_of import BodyAnyOf
from mockserver.models.body_any_of1 import BodyAnyOf1
from mockserver.models.body_any_of2 import BodyAnyOf2
from mockserver.models.body_any_of3 import BodyAnyOf3
from mockserver.models.body_any_of4 import BodyAnyOf4
from mockserver.models.body_any_of5 import BodyAnyOf5
from mockserver.models.body_any_of6 import BodyAnyOf6
from mockserver.models.body_any_of7 import BodyAnyOf7
from mockserver.models.body_any_of8 import BodyAnyOf8
from mockserver.models.body_any_of9 import BodyAnyOf9
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

BODY_ANY_OF_SCHEMAS = ["BodyAnyOf", "BodyAnyOf1", "BodyAnyOf2", "BodyAnyOf3", "BodyAnyOf4", "BodyAnyOf5", "BodyAnyOf6", "BodyAnyOf7", "BodyAnyOf8", "BodyAnyOf9", "Dict[str, object]", "str"]

class Body(BaseModel):
    """
    request body matcher
    """

    # data type: BodyAnyOf
    anyof_schema_1_validator: Optional[BodyAnyOf] = None
    # data type: BodyAnyOf1
    anyof_schema_2_validator: Optional[BodyAnyOf1] = None
    # data type: Dict[str, object]
    anyof_schema_3_validator: Optional[Dict[str, Any]] = Field(default=None, description="json matching fields body matcher")
    # data type: BodyAnyOf2
    anyof_schema_4_validator: Optional[BodyAnyOf2] = None
    # data type: BodyAnyOf3
    anyof_schema_5_validator: Optional[BodyAnyOf3] = None
    # data type: BodyAnyOf4
    anyof_schema_6_validator: Optional[BodyAnyOf4] = None
    # data type: BodyAnyOf5
    anyof_schema_7_validator: Optional[BodyAnyOf5] = None
    # data type: BodyAnyOf6
    anyof_schema_8_validator: Optional[BodyAnyOf6] = None
    # data type: str
    anyof_schema_9_validator: Optional[StrictStr] = Field(default=None, description="substring body matcher")
    # data type: BodyAnyOf7
    anyof_schema_10_validator: Optional[BodyAnyOf7] = None
    # data type: BodyAnyOf8
    anyof_schema_11_validator: Optional[BodyAnyOf8] = None
    # data type: BodyAnyOf9
    anyof_schema_12_validator: Optional[BodyAnyOf9] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[BodyAnyOf, BodyAnyOf1, BodyAnyOf2, BodyAnyOf3, BodyAnyOf4, BodyAnyOf5, BodyAnyOf6, BodyAnyOf7, BodyAnyOf8, BodyAnyOf9, Dict[str, object], str]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "BodyAnyOf", "BodyAnyOf1", "BodyAnyOf2", "BodyAnyOf3", "BodyAnyOf4", "BodyAnyOf5", "BodyAnyOf6", "BodyAnyOf7", "BodyAnyOf8", "BodyAnyOf9", "Dict[str, object]", "str" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Body.model_construct()
        error_messages = []
        # validate data type: BodyAnyOf
        if not isinstance(v, BodyAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf`")
        else:
            return v

        # validate data type: BodyAnyOf1
        if not isinstance(v, BodyAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf1`")
        else:
            return v

        # validate data type: Dict[str, object]
        try:
            instance.anyof_schema_3_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: BodyAnyOf2
        if not isinstance(v, BodyAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf2`")
        else:
            return v

        # validate data type: BodyAnyOf3
        if not isinstance(v, BodyAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf3`")
        else:
            return v

        # validate data type: BodyAnyOf4
        if not isinstance(v, BodyAnyOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf4`")
        else:
            return v

        # validate data type: BodyAnyOf5
        if not isinstance(v, BodyAnyOf5):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf5`")
        else:
            return v

        # validate data type: BodyAnyOf6
        if not isinstance(v, BodyAnyOf6):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf6`")
        else:
            return v

        # validate data type: str
        try:
            instance.anyof_schema_9_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: BodyAnyOf7
        if not isinstance(v, BodyAnyOf7):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf7`")
        else:
            return v

        # validate data type: BodyAnyOf8
        if not isinstance(v, BodyAnyOf8):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf8`")
        else:
            return v

        # validate data type: BodyAnyOf9
        if not isinstance(v, BodyAnyOf9):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyAnyOf9`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Body with anyOf schemas: BodyAnyOf, BodyAnyOf1, BodyAnyOf2, BodyAnyOf3, BodyAnyOf4, BodyAnyOf5, BodyAnyOf6, BodyAnyOf7, BodyAnyOf8, BodyAnyOf9, Dict[str, object], str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[BodyAnyOf] = None
        try:
            instance.actual_instance = BodyAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[BodyAnyOf1] = None
        try:
            instance.actual_instance = BodyAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into Dict[str, object]
        try:
            # validation
            instance.anyof_schema_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_3_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[BodyAnyOf2] = None
        try:
            instance.actual_instance = BodyAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[BodyAnyOf3] = None
        try:
            instance.actual_instance = BodyAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[BodyAnyOf4] = None
        try:
            instance.actual_instance = BodyAnyOf4.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[BodyAnyOf5] = None
        try:
            instance.actual_instance = BodyAnyOf5.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_8_validator: Optional[BodyAnyOf6] = None
        try:
            instance.actual_instance = BodyAnyOf6.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.anyof_schema_9_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_9_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_10_validator: Optional[BodyAnyOf7] = None
        try:
            instance.actual_instance = BodyAnyOf7.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_11_validator: Optional[BodyAnyOf8] = None
        try:
            instance.actual_instance = BodyAnyOf8.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_12_validator: Optional[BodyAnyOf9] = None
        try:
            instance.actual_instance = BodyAnyOf9.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Body with anyOf schemas: BodyAnyOf, BodyAnyOf1, BodyAnyOf2, BodyAnyOf3, BodyAnyOf4, BodyAnyOf5, BodyAnyOf6, BodyAnyOf7, BodyAnyOf8, BodyAnyOf9, Dict[str, object], str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BodyAnyOf, BodyAnyOf1, BodyAnyOf2, BodyAnyOf3, BodyAnyOf4, BodyAnyOf5, BodyAnyOf6, BodyAnyOf7, BodyAnyOf8, BodyAnyOf9, Dict[str, object], str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


