# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, Optional
from mockserver.models.body_with_content_type_any_of import BodyWithContentTypeAnyOf
from mockserver.models.body_with_content_type_any_of1 import BodyWithContentTypeAnyOf1
from mockserver.models.body_with_content_type_any_of2 import BodyWithContentTypeAnyOf2
from mockserver.models.body_with_content_type_any_of3 import BodyWithContentTypeAnyOf3
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

BODYWITHCONTENTTYPE_ANY_OF_SCHEMAS = ["BodyWithContentTypeAnyOf", "BodyWithContentTypeAnyOf1", "BodyWithContentTypeAnyOf2", "BodyWithContentTypeAnyOf3", "Dict[str, object]", "str"]

class BodyWithContentType(BaseModel):
    """
    response body
    """

    # data type: BodyWithContentTypeAnyOf
    anyof_schema_1_validator: Optional[BodyWithContentTypeAnyOf] = None
    # data type: BodyWithContentTypeAnyOf1
    anyof_schema_2_validator: Optional[BodyWithContentTypeAnyOf1] = None
    # data type: Dict[str, object]
    anyof_schema_3_validator: Optional[Dict[str, Any]] = Field(default=None, description="json response body")
    # data type: BodyWithContentTypeAnyOf2
    anyof_schema_4_validator: Optional[BodyWithContentTypeAnyOf2] = None
    # data type: str
    anyof_schema_5_validator: Optional[StrictStr] = Field(default=None, description="string response body")
    # data type: BodyWithContentTypeAnyOf3
    anyof_schema_6_validator: Optional[BodyWithContentTypeAnyOf3] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[BodyWithContentTypeAnyOf, BodyWithContentTypeAnyOf1, BodyWithContentTypeAnyOf2, BodyWithContentTypeAnyOf3, Dict[str, object], str]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "BodyWithContentTypeAnyOf", "BodyWithContentTypeAnyOf1", "BodyWithContentTypeAnyOf2", "BodyWithContentTypeAnyOf3", "Dict[str, object]", "str" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = BodyWithContentType.model_construct()
        error_messages = []
        # validate data type: BodyWithContentTypeAnyOf
        if not isinstance(v, BodyWithContentTypeAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyWithContentTypeAnyOf`")
        else:
            return v

        # validate data type: BodyWithContentTypeAnyOf1
        if not isinstance(v, BodyWithContentTypeAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyWithContentTypeAnyOf1`")
        else:
            return v

        # validate data type: Dict[str, object]
        try:
            instance.anyof_schema_3_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: BodyWithContentTypeAnyOf2
        if not isinstance(v, BodyWithContentTypeAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyWithContentTypeAnyOf2`")
        else:
            return v

        # validate data type: str
        try:
            instance.anyof_schema_5_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: BodyWithContentTypeAnyOf3
        if not isinstance(v, BodyWithContentTypeAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BodyWithContentTypeAnyOf3`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in BodyWithContentType with anyOf schemas: BodyWithContentTypeAnyOf, BodyWithContentTypeAnyOf1, BodyWithContentTypeAnyOf2, BodyWithContentTypeAnyOf3, Dict[str, object], str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[BodyWithContentTypeAnyOf] = None
        try:
            instance.actual_instance = BodyWithContentTypeAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[BodyWithContentTypeAnyOf1] = None
        try:
            instance.actual_instance = BodyWithContentTypeAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into Dict[str, object]
        try:
            # validation
            instance.anyof_schema_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_3_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[BodyWithContentTypeAnyOf2] = None
        try:
            instance.actual_instance = BodyWithContentTypeAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into str
        try:
            # validation
            instance.anyof_schema_5_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_5_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[BodyWithContentTypeAnyOf3] = None
        try:
            instance.actual_instance = BodyWithContentTypeAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into BodyWithContentType with anyOf schemas: BodyWithContentTypeAnyOf, BodyWithContentTypeAnyOf1, BodyWithContentTypeAnyOf2, BodyWithContentTypeAnyOf3, Dict[str, object], str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BodyWithContentTypeAnyOf, BodyWithContentTypeAnyOf1, BodyWithContentTypeAnyOf2, BodyWithContentTypeAnyOf3, Dict[str, object], str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


