# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from mockserver.models.http_override_forwarded_request_one_of import HttpOverrideForwardedRequestOneOf
from mockserver.models.http_override_forwarded_request_one_of1 import HttpOverrideForwardedRequestOneOf1
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

HTTPOVERRIDEFORWARDEDREQUEST_ONE_OF_SCHEMAS = ["HttpOverrideForwardedRequestOneOf", "HttpOverrideForwardedRequestOneOf1"]

class HttpOverrideForwardedRequest(BaseModel):
    """
    override forwarded request
    """
    # data type: HttpOverrideForwardedRequestOneOf
    oneof_schema_1_validator: Optional[HttpOverrideForwardedRequestOneOf] = None
    # data type: HttpOverrideForwardedRequestOneOf1
    oneof_schema_2_validator: Optional[HttpOverrideForwardedRequestOneOf1] = None
    actual_instance: Optional[Union[HttpOverrideForwardedRequestOneOf, HttpOverrideForwardedRequestOneOf1]] = None
    one_of_schemas: Set[str] = { "HttpOverrideForwardedRequestOneOf", "HttpOverrideForwardedRequestOneOf1" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = HttpOverrideForwardedRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: HttpOverrideForwardedRequestOneOf
        if not isinstance(v, HttpOverrideForwardedRequestOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HttpOverrideForwardedRequestOneOf`")
        else:
            match += 1
        # validate data type: HttpOverrideForwardedRequestOneOf1
        if not isinstance(v, HttpOverrideForwardedRequestOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HttpOverrideForwardedRequestOneOf1`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in HttpOverrideForwardedRequest with oneOf schemas: HttpOverrideForwardedRequestOneOf, HttpOverrideForwardedRequestOneOf1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in HttpOverrideForwardedRequest with oneOf schemas: HttpOverrideForwardedRequestOneOf, HttpOverrideForwardedRequestOneOf1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into HttpOverrideForwardedRequestOneOf
        try:
            instance.actual_instance = HttpOverrideForwardedRequestOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into HttpOverrideForwardedRequestOneOf1
        try:
            instance.actual_instance = HttpOverrideForwardedRequestOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into HttpOverrideForwardedRequest with oneOf schemas: HttpOverrideForwardedRequestOneOf, HttpOverrideForwardedRequestOneOf1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into HttpOverrideForwardedRequest with oneOf schemas: HttpOverrideForwardedRequestOneOf, HttpOverrideForwardedRequestOneOf1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], HttpOverrideForwardedRequestOneOf, HttpOverrideForwardedRequestOneOf1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


