# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, Optional
from mockserver.models.body import Body
from mockserver.models.key_to_multi_value import KeyToMultiValue
from mockserver.models.key_to_value import KeyToValue
from mockserver.models.protocol import Protocol
from mockserver.models.socket_address import SocketAddress
from mockserver.models.string_or_json_schema import StringOrJsonSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class HttpRequest(BaseModel):
    """
    request properties matcher
    """ # noqa: E501
    secure: Optional[StrictBool] = None
    keep_alive: Optional[StrictBool] = Field(default=None, alias="keepAlive")
    method: Optional[StringOrJsonSchema] = None
    path: Optional[StringOrJsonSchema] = None
    path_parameters: Optional[KeyToMultiValue] = Field(default=None, alias="pathParameters")
    query_string_parameters: Optional[KeyToMultiValue] = Field(default=None, alias="queryStringParameters")
    body: Optional[Body] = None
    headers: Optional[KeyToMultiValue] = None
    cookies: Optional[KeyToValue] = None
    socket_address: Optional[SocketAddress] = Field(default=None, alias="socketAddress")
    protocol: Optional[Protocol] = None
    __properties: ClassVar[List[str]] = ["secure", "keepAlive", "method", "path", "pathParameters", "queryStringParameters", "body", "headers", "cookies", "socketAddress", "protocol"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HttpRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of method
        if self.method:
            _dict['method'] = self.method.to_dict()
        # override the default output from pydantic by calling `to_dict()` of path
        if self.path:
            _dict['path'] = self.path.to_dict()
        # override the default output from pydantic by calling `to_dict()` of path_parameters
        if self.path_parameters:
            _dict['pathParameters'] = self.path_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of query_string_parameters
        if self.query_string_parameters:
            _dict['queryStringParameters'] = self.query_string_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of body
        if self.body:
            _dict['body'] = self.body.to_dict()
        # override the default output from pydantic by calling `to_dict()` of headers
        if self.headers:
            _dict['headers'] = self.headers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cookies
        if self.cookies:
            _dict['cookies'] = self.cookies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of socket_address
        if self.socket_address:
            _dict['socketAddress'] = self.socket_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HttpRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "secure": obj.get("secure"),
            "keepAlive": obj.get("keepAlive"),
            "method": StringOrJsonSchema.from_dict(obj["method"]) if obj.get("method") is not None else None,
            "path": StringOrJsonSchema.from_dict(obj["path"]) if obj.get("path") is not None else None,
            "pathParameters": KeyToMultiValue.from_dict(obj["pathParameters"]) if obj.get("pathParameters") is not None else None,
            "queryStringParameters": KeyToMultiValue.from_dict(obj["queryStringParameters"]) if obj.get("queryStringParameters") is not None else None,
            "body": Body.from_dict(obj["body"]) if obj.get("body") is not None else None,
            "headers": KeyToMultiValue.from_dict(obj["headers"]) if obj.get("headers") is not None else None,
            "cookies": KeyToValue.from_dict(obj["cookies"]) if obj.get("cookies") is not None else None,
            "socketAddress": SocketAddress.from_dict(obj["socketAddress"]) if obj.get("socketAddress") is not None else None,
            "protocol": obj.get("protocol")
        })
        return _obj


