# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from mockserver.models.http_override_forwarded_request_one_of_request_modifier_cookies import HttpOverrideForwardedRequestOneOfRequestModifierCookies
from mockserver.models.http_override_forwarded_request_one_of_request_modifier_path import HttpOverrideForwardedRequestOneOfRequestModifierPath
from mockserver.models.http_override_forwarded_request_one_of_request_modifier_query_string_parameters import HttpOverrideForwardedRequestOneOfRequestModifierQueryStringParameters
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class HttpOverrideForwardedRequestOneOfRequestModifier(BaseModel):
    """
    HttpOverrideForwardedRequestOneOfRequestModifier
    """ # noqa: E501
    path: Optional[HttpOverrideForwardedRequestOneOfRequestModifierPath] = None
    query_string_parameters: Optional[HttpOverrideForwardedRequestOneOfRequestModifierQueryStringParameters] = Field(default=None, alias="queryStringParameters")
    headers: Optional[HttpOverrideForwardedRequestOneOfRequestModifierQueryStringParameters] = None
    cookies: Optional[HttpOverrideForwardedRequestOneOfRequestModifierCookies] = None
    __properties: ClassVar[List[str]] = ["path", "queryStringParameters", "headers", "cookies"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HttpOverrideForwardedRequestOneOfRequestModifier from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of path
        if self.path:
            _dict['path'] = self.path.to_dict()
        # override the default output from pydantic by calling `to_dict()` of query_string_parameters
        if self.query_string_parameters:
            _dict['queryStringParameters'] = self.query_string_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of headers
        if self.headers:
            _dict['headers'] = self.headers.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cookies
        if self.cookies:
            _dict['cookies'] = self.cookies.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HttpOverrideForwardedRequestOneOfRequestModifier from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": HttpOverrideForwardedRequestOneOfRequestModifierPath.from_dict(obj["path"]) if obj.get("path") is not None else None,
            "queryStringParameters": HttpOverrideForwardedRequestOneOfRequestModifierQueryStringParameters.from_dict(obj["queryStringParameters"]) if obj.get("queryStringParameters") is not None else None,
            "headers": HttpOverrideForwardedRequestOneOfRequestModifierQueryStringParameters.from_dict(obj["headers"]) if obj.get("headers") is not None else None,
            "cookies": HttpOverrideForwardedRequestOneOfRequestModifierCookies.from_dict(obj["cookies"]) if obj.get("cookies") is not None else None
        })
        return _obj


