# coding: utf-8

"""
    MockServer API

    MockServer enables easy mocking of any system you integrate with via HTTP or HTTPS with clients written in Java, JavaScript and Ruby and a simple REST API (as shown below).  MockServer Proxy is a proxy that introspects all proxied traffic including encrypted SSL traffic and supports Port Forwarding, Web Proxying (i.e. HTTP proxy), HTTPS Tunneling Proxying (using HTTP CONNECT) and SOCKS Proxying (i.e. dynamic port forwarding).  Both MockServer and the MockServer Proxy record all received requests so that it is possible to verify exactly what requests have been sent by the system under test.

    The version of the OpenAPI document: 5.15.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from mockserver.models.delay import Delay
from mockserver.models.http_override_forwarded_request_one_of_request_modifier import HttpOverrideForwardedRequestOneOfRequestModifier
from mockserver.models.http_override_forwarded_request_one_of_response_modifier import HttpOverrideForwardedRequestOneOfResponseModifier
from mockserver.models.http_request import HttpRequest
from mockserver.models.http_response import HttpResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class HttpOverrideForwardedRequestOneOf(BaseModel):
    """
    HttpOverrideForwardedRequestOneOf
    """ # noqa: E501
    delay: Optional[Delay] = None
    request_override: Optional[HttpRequest] = Field(default=None, alias="requestOverride")
    request_modifier: Optional[HttpOverrideForwardedRequestOneOfRequestModifier] = Field(default=None, alias="requestModifier")
    response_override: Optional[HttpResponse] = Field(default=None, alias="responseOverride")
    response_modifier: Optional[HttpOverrideForwardedRequestOneOfResponseModifier] = Field(default=None, alias="responseModifier")
    __properties: ClassVar[List[str]] = ["delay", "requestOverride", "requestModifier", "responseOverride", "responseModifier"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HttpOverrideForwardedRequestOneOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delay
        if self.delay:
            _dict['delay'] = self.delay.to_dict()
        # override the default output from pydantic by calling `to_dict()` of request_override
        if self.request_override:
            _dict['requestOverride'] = self.request_override.to_dict()
        # override the default output from pydantic by calling `to_dict()` of request_modifier
        if self.request_modifier:
            _dict['requestModifier'] = self.request_modifier.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response_override
        if self.response_override:
            _dict['responseOverride'] = self.response_override.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response_modifier
        if self.response_modifier:
            _dict['responseModifier'] = self.response_modifier.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HttpOverrideForwardedRequestOneOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "delay": Delay.from_dict(obj["delay"]) if obj.get("delay") is not None else None,
            "requestOverride": HttpRequest.from_dict(obj["requestOverride"]) if obj.get("requestOverride") is not None else None,
            "requestModifier": HttpOverrideForwardedRequestOneOfRequestModifier.from_dict(obj["requestModifier"]) if obj.get("requestModifier") is not None else None,
            "responseOverride": HttpResponse.from_dict(obj["responseOverride"]) if obj.get("responseOverride") is not None else None,
            "responseModifier": HttpOverrideForwardedRequestOneOfResponseModifier.from_dict(obj["responseModifier"]) if obj.get("responseModifier") is not None else None
        })
        return _obj


